### ISSUE TITLE
Dollar character in a filter

### ISSUE THREAD

**Issue by aborruso** [owenthereal/jqplay#68]
Hi,
when I try this snippet https://jqplay.org/s/zkBQG8vTN8 on my shell, I have the below error.

I think the problem is related to `$`, but I do not find a way to run this filter on my shell. It works on jq play.

Thank you

```
error: syntax error, unexpected QQSTRING_START, expecting IDENT
.html.body.li[]."$t"
                ^
1 compile error
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1018:11)
    at WriteWrap.afterWrite (net.js:804:14)
```

**Comment by owenthereal** [comment]
Could you share a full example for reference? This shouldn’t be an issue anymore, as the query is now piped directly to jq-wasm, which runs entirely in your browser as is. Feel free to reopen the ticket if it still happens.
